name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * 1-5"

jobs:
  cache-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build Zenoh-C dependencies
        uses: ./.github/actions/build-zenoh-c
        with:
          install-prefix: "/tmp/local"

  build:
    name: Build examples
    needs: cache-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build Zenoh-C dependencies
        uses: ./.github/actions/build-zenoh-c
        with:
          install-prefix: "/tmp/local"

      - name: Clean Go Cache
        run: go clean --cache

      - name: Install dependencies
        run: make deps

      - name: Build all examples
        run: |
          export CGO_CFLAGS="-I/tmp/local/include"
          export CGO_LDFLAGS="-L/tmp/local/lib"
          make

  test:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Clean Go Cache
        run: go clean --cache

      - name: Build Zenoh-C dependencies
        uses: ./.github/actions/build-zenoh-c
        with:
          install-prefix: "/tmp/local"

      - name: Run tests
        run: |
          export CGO_CFLAGS="-I/tmp/local/include"
          export CGO_LDFLAGS="-L/tmp/local/lib"
          export LD_LIBRARY_PATH="/tmp/local/lib"
          make test

      - name: Build all examples
        run: |
          export CGO_CFLAGS="-I/tmp/local/include"
          export CGO_LDFLAGS="-L/tmp/local/lib"
          make

      - name: Test examples
        run: |
          export LD_LIBRARY_PATH="/tmp/local/lib"
          make test_examples

      - name: Test examples with QUIC
        run: |
          export LD_LIBRARY_PATH="/tmp/local/lib"
          make test_examples_quic

  fmt:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Check code format
        run: make fmt
